# 基本设置
version = "0.1.0"
environment = "development"  # development 或 production

# 服务器设置
[server]
address = "124.70.199.200"
auth_port = 8080
signal_port = 8081
ice_port = 8082

# UI设置
[ui]
theme = "dark"
language = "zh-CN"
hide_toolbar_in_fullscreen = true
show_performance_stats = true

[ui.development]
show_toolbar = true
show_fps = true
show_status = true
show_remote_screen = true
allow_mode_switch = true

[ui.production]
show_toolbar = true
show_fps = false
show_status = true
show_remote_screen = true
allow_mode_switch = false

# 性能设置
[performance]
max_goroutines = 1000
frame_buffer_size = 10
skip_identical_frames = true

# 日志设置
[log]
console = true
file = true
file_path = "logs"
max_size = 50
max_backups = 30
max_age = 7
compress = true
local_time = true
format = "rdC_%s.log"
level = "debug"
output_format = "text"