# 基本设置
version = "0.1.0"
environment = "development"  # development 或 production

# 服务设置
[server]
host = "0.0.0.0"
auth_port = 7070
signal_port = 7071
ice_port = 7072

max_connections = 1000
idle_timeout = 300
goroutine_pool_size = 500
message_buffer_size = 100
cleanup_interval = 30

expiry_duration = 10
max_blocking_tasks = 1000

# 日志设置
[log]
console = true
file = true
file_path = "logs"
max_size = 50
max_backups = 30
max_age = 7
compress = true
local_time = true
format = "rdS_%s.log"
level = "debug"
output_format = "text"