# 基本设置
version = "0.1.0"
environment = "development"  # development 或 production

# 日志设置
[log]
console = true
file = true
file_path = "logs"
max_size = 50
max_backups = 30
max_age = 7
compress = true
local_time = true
format = "rdS_%s.log"
level = "debug"
output_format = "text"